### ISSUE TITLE
Referrer

### ISSUE THREAD

**Issue by yesyeahvh123** [dewanakl/DikitLink#1]
Hello sir can you add function allow/block referrer from urls
Example: i want block traffic from Facebook and allow from Google
Thank you for creating great script

**Comment by dewanakl** [comment]
Hello, thanks for trying this app. Sorry, your function or feature request is not possible because the referrer cannot be blocked.

Don't worry, this app can increase the time to open or close the link and set a password to open it.

You can request such a feature, thank you sir

**Comment by yesyeahvh123** [comment]
sir, why not use http referer header

**Comment by dewanakl** [comment]
sorry sir, I would not recommend using HTTP_REFERER because I read this on stackoverflow

https://stackoverflow.com/questions/36240145/how-to-use-serverhttp-referer-correctly-in-php

**Comment by yesyeahvh123** [comment]
Sir can you tell me how to deloy to vercell? i deploy to vercel but its not working, do i need to add anything else? Can you add implementation guide on free platforms like railway, glitch? Thank you very much.

**Comment by dewanakl** [comment]
This app like laravel sir, I will write how to use it, in the next 1 or 2 days

**Comment by dewanakl** [comment]
**How to run ?**

- clone or download this repository
- cp .env.example .env
- php saya key
- php saya migrasi --gen
- php coba (run development serve)

**Comment by yesyeahvh123** [comment]
Sir I'm a newbie with no experience, can you guide me more clearly, or can you create a deloy button on Vercel?

**Comment by dewanakl** [comment]
I understand sir, before that you can try on localhost first and the steps are already above, sir.

**Comment by yesyeahvh123** [comment]
Sir, I'm really sorry but it's difficult for inexperienced people like me, do you have specific instructions, or buttons to deploy to platforms like vercel, glitch, railway...thank you very much

**Comment by dewanakl** [comment]
sorry sir, i forgot to say that you need to add env in vercel like this picture, to get the value taken from the ".env" file already using the command "php saya key" (to fill the value app_key automatically). Thank you sir

https://ibb.co/KhYh7GM
https://ibb.co/4ZF8ZNV

**Comment by yesyeahvh123** [comment]
Sir I'm a newbie with no experience, can you guide me more clearly, or can you create a deloy button on Vercel?

**Comment by dewanakl** [comment]
Ok sir, I will make a video for you via youtube

**Comment by yesyeahvh123** [comment]
I'm looking forward to your video

**Comment by dewanakl** [comment]
https://drive.google.com/file/d/1OE8rgypiPwD7gqLWlByY09bxv7wuzvoY/view?usp=sharing

https://drive.google.com/file/d/1nDzlkfkVyiSj6eDJ2KM_3OmZaRhWHVvy/view?usp=sharing

**Comment by dewanakl** [comment]
Sorry sir, I just had time to make it now.
there are 2 parts sir, and I also found a small error in the vercel env in the second video. Thank you

**Comment by yesyeahvh123** [comment]
thank you so much for making video sir
i try 2 times but get error Page Expired ! when login/register can you tell me what i do something wrong?

**Comment by dewanakl** [comment]
Are cookies in your web browser active, sir?

**Comment by dewanakl** [comment]
I'm sorry, I didn't upload the video to YouTube

**Comment by yesyeahvh123** [comment]
![Capture1](https://user-images.githubusercontent.com/69633089/193192919-b22bbbf0-e7e4-42f7-a335-f4392904dd5b.PNG)
![Capture2](https://user-images.githubusercontent.com/69633089/193192973-d7dedd6b-af80-4849-895c-bc46e8af9c71.PNG)
![Capture3](https://user-images.githubusercontent.com/69633089/193193117-bb05d3f4-8281-4fda-abcb-d772f3923c66.PNG)

**Comment by yesyeahvh123** [comment]
yes cookies active

**Comment by yesyeahvh123** [comment]
i dont known what wrong

**Comment by yesyeahvh123** [comment]
![Uploading Capture4.PNG…]()

**Comment by yesyeahvh123** [comment]
![Capture4](https://user-images.githubusercontent.com/69633089/193193446-095e63b1-49b1-499f-8086-de8ec4a381a7.PNG)

**Comment by yesyeahvh123** [comment]
![Capture5](https://user-images.githubusercontent.com/69633089/193193625-26139e31-5317-4b78-8032-3c8a48e4a711.PNG)

**Comment by dewanakl** [comment]
try application name (APP_NAME) not using spaces and add a new env with key "HTTPS" value "true"

**Comment by dewanakl** [comment]
This app_key is very private and no one should know about it, so please delete the photo before others find out, thank you sir

**Comment by yesyeahvh123** [comment]
thank you so much sir
problem is aplication name (APP_NAME) using spaces

**Comment by yesyeahvh123** [comment]
can you add the feature to batch select links to completely delete, remove the password of the selected links, set the password in bulk, edit the password in bulk...generally edit multiple links at the same time?

**Comment by yesyeahvh123** [comment]
and can use Upstash (in Vercel) for database?

**Comment by dewanakl** [comment]
it can but i'm struggling in good ui ux in this case

**Comment by dewanakl** [comment]
I've tried "supabase" from vercel but the pgsql version in vercel is still small, here's the phpinfo link from vercel

https://phpshow.vercel.app/

**Comment by yesyeahvh123** [comment]
This project use Upstash for database
https://github.com/steven-tey/dub#deploy-your-own

**Comment by dewanakl** [comment]
the project uses typescript sir

**Comment by yesyeahvh123** [comment]
i connect mariadb with DB_DRIV value mysql but get error
![Capture](https://user-images.githubusercontent.com/69633089/193385839-f8240620-5ea0-48e8-86f3-7617adc5cc5e.PNG)
can you help me

**Comment by yesyeahvh123** [comment]
![Capture2](https://user-images.githubusercontent.com/69633089/193385889-540888bc-f135-4f80-ba32-e6aa16719eb6.PNG)

**Comment by yesyeahvh123** [comment]
something wrong?

**Comment by dewanakl** [comment]
make sure the env entry is correct sir

**Comment by yesyeahvh123** [comment]
I have checked very carefully, there is nothing wrong, because if wrong, the database will not be created

**Comment by yesyeahvh123** [comment]
I use mysql at alwaysdata.com

**Comment by yesyeahvh123** [comment]
can you go to alwaysdata.com to try creating mysql?

**Comment by yesyeahvh123** [comment]
DB_DRIV = mysql
DB_PORT = 3306
is right?

**Comment by yesyeahvh123** [comment]
it is mysql mariadb 10.6

**Comment by dewanakl** [comment]
![Screenshot 2022-10-02 154007](https://user-images.githubusercontent.com/53048107/193445732-8fe51798-275d-43a7-b190-61d88de40179.png)
![Screenshot 2022-10-02 154017](https://user-images.githubusercontent.com/53048107/193445736-49444ec4-e709-4af1-b9c4-9817e42e0ba4.png)
![Screenshot 2022-10-02 154057](https://user-images.githubusercontent.com/53048107/193445737-c315481a-ce54-4205-81c9-56124209d7e7.png)

**Comment by dewanakl** [comment]
![Screenshot 2022-10-02 154330](https://user-images.githubusercontent.com/53048107/193445805-94077c8c-3c1f-4cbd-8b58-48f58cdb8ae2.png)

**Comment by dewanakl** [comment]
work well sir

**Comment by yesyeahvh123** [comment]
sorry sir my mistake, do you think alwaysdata.com site is better than elephantsql.com? is there any better site for mysql database?

**Comment by dewanakl** [comment]
Honestly sir, I can't say that because I was looking for a free postgresql hosting that is elephantsql, but I think postgresql on heroku is very good and safe but the free service will end as far as I know, thank you sir

**Comment by yesyeahvh123** [comment]
Sir I don't want to use statics because it will consume database space, what should I do?

**Comment by dewanakl** [comment]
good idea sir, I can add a feature whether you want statistics or not by editing it

**Comment by apkpeaks** [comment]
great feature, i'm looking forward to it

**Comment by yesyeahvh123** [comment]
great feature, i'm looking forward to it

**Comment by yesyeahvh123** [comment]
have you tried the glitch, it's the same as vercel, can you try implementing it?

**Comment by dewanakl** [comment]
Sorry sir, where is the error, may I know?

**Comment by yesyeahvh123** [comment]
I don't know if there is an error but I don't know how to implement it sir

**Comment by yesyeahvh123** [comment]
glitch.me this website same as vercel.com

**Comment by dewanakl** [comment]
https://support.glitch.com/t/can-i-run-php-on-glitch/2170/21

glitch not support php sir

**Comment by yesyeahvh123** [comment]
Hello sir

**Comment by yesyeahvh123** [comment]
Do you have WhatsApp, discord or something to contact?

**Comment by dewanakl** [comment]
You can contact me via https://www.instagram.com/dewana_kl/

**Comment by yesyeahvh123** [comment]
Sir how to deploy project to hosting?

**Comment by dewanakl** [comment]
Like a laravel deploy on hosting sir
